name: NoMaceNoStrength
version: 2.1
author: Felixwrn
main: de.deinname.nomacenostrength.Main
api-version: 1.21

commands:
  togglemace:
    description: Schaltet Maces ein/aus
  setstrength:
    description: Setzt das maximale Stärke-Level
  toggleweakness:
    description: Aktiviert/Deaktiviert Schwäche
