name: CombatSystem
version: 3.1
author: Felixwrn
main: de.deinname.nomacenostrength.Main
api-version: 1.21

depend: 
   - coreapi

commands:
  combatlimiter:
    description: Öffnet das CombatLimiter GUI
  accept:
    description: Nimm eine PvP Anfrage an
  deny:
    description: Lehne eine PvP Anfrage ab
  pvp:
    description: Öffnet PvP Menü
